[2025-08-27 09:53:58] === Запуск генерации рекомендаций ===
[2025-08-27 09:53:58] Загружено 470347 пользователей
[2025-08-27 09:53:58] Загружен recent_items_map
[2025-08-27 09:53:58] Загружен copurchase_map
[2025-08-27 09:54:00] Загружен item_to_cat
[2025-08-27 09:54:00] Загружен cat_to_items
[2025-08-27 09:54:00] Загружен user_features_dict
[2025-08-27 09:54:01] Загружен item_features_dict
[2025-08-27 09:54:01] Загружен item_map
[2025-08-27 09:54:01] Загружен popular_items
[2025-08-27 09:54:01] === ГЕНЕРАЦИЯ РЕКОМЕНДАЦИЙ (super_fast + cache) ===
[2025-08-27 11:22:11] Генерация завершена за 1:28:10.374328
[2025-08-27 11:22:11] === Завершено успешно ===
[2025-08-27 23:48:19] === Запуск генерации рекомендаций ===
[2025-08-27 23:48:19] Ошибка: 'user_id'
[2025-08-27 23:49:20] === Запуск генерации рекомендаций ===
[2025-08-27 23:49:20] Загружено 470347 пользователей
[2025-08-27 23:49:20] Загружен recent_items_map
[2025-08-27 23:49:20] Загружен copurchase_map
[2025-08-27 23:49:20] Загружен item_to_cat
[2025-08-27 23:49:20] Ошибка загрузки cat_to_items: [Errno 2] No such file or directory: '/home/root6/python/e_cup/rec_system/data/processed/extended_cat_to_items.pkl'
[2025-08-27 23:49:20] Ошибка: [Errno 2] No such file or directory: '/home/root6/python/e_cup/rec_system/data/processed/extended_cat_to_items.pkl'
[2025-08-27 23:49:45] === Запуск генерации рекомендаций ===
[2025-08-27 23:49:45] Загружено 470347 пользователей
[2025-08-27 23:49:45] Загружен recent_items_map
[2025-08-27 23:49:45] Загружен copurchase_map
[2025-08-27 23:49:45] Загружен item_to_cat
[2025-08-27 23:49:45] Загружен cat_to_items
[2025-08-27 23:49:45] Загружен user_features_dict
[2025-08-27 23:49:45] Загружен item_features_dict
[2025-08-27 23:49:45] Загружен item_map
[2025-08-27 23:49:45] Загружен popular_items
[2025-08-27 23:49:45] === ГЕНЕРАЦИЯ РЕКОМЕНДАЦИЙ (super_fast + cache) ===
